MACRO(BOARD_GET_CHIP BOARD CHIP)
    STRING(TOUPPER ${BOARD} BOARD)
    FILE(STRINGS "stm32boards.csv" ROW REGEX "^${BOARD},.+$")
    MESSAGE(${ROW})
    IF(${ROW} MATCHES "${BOARD},.+")
        STRING(REGEX REPLACE ".+,(.+)" "\\1" ${CHIP} ${ROW})
        MESSAGE(-${CHIP}-)
    ELSE()
        MESSAGE(FATAL_ERROR "Invalid/unsupported board: ${BOARD}")
    ENDIF()
ENDMACRO()

IF(TESTING)
    IF(NOT BOARD)
        MESSAGE(FATAL_ERROR "BOARD Undefined!")
    ENDIF()

    BOARD_GET_CHIP(${BOARD} _CHIP)
    MESSAGE(Board:\ ${BOARD}\ Mcu:\ ${_CHIP})
ENDIF()
